### ISSUE TITLE
WavefrontJvmReporter is not properly disposed on context shutdown

### ISSUE THREAD

**Issue by snicoll** [wavefrontHQ/wavefront-spring-boot#108]
An app that uses wavefront and devtools will emit the following logs after the first restart:

```
2021-04-09 15:17:17.426  WARN 64359 --- [rics-registry-0] c.w.s.c.m.WavefrontSdkMetricsRegistry    : Unable to send internal SDK metric

java.io.IOException: attempt to send using closed sender
	at com.wavefront.sdk.common.clients.WavefrontClient.sendMetric(WavefrontClient.java:323) ~[wavefront-sdk-java-2.6.2.jar:na]
	at com.wavefront.sdk.common.metrics.WavefrontSdkMetricsRegistry.run(WavefrontSdkMetricsRegistry.java:163) ~[wavefront-sdk-java-2.6.2.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-04-09 15:17:17.426  WARN 64359 --- [rics-registry-0] c.w.s.c.m.WavefrontSdkMetricsRegistry    : Unable to send internal SDK metric

java.io.IOException: attempt to send using closed sender
	at com.wavefront.sdk.common.clients.WavefrontClient.sendMetric(WavefrontClient.java:323) ~[wavefront-sdk-java-2.6.2.jar:na]
	at com.wavefront.sdk.common.metrics.WavefrontSdkMetricsRegistry.run(WavefrontSdkMetricsRegistry.java:163) ~[wavefront-sdk-java-2.6.2.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-04-09 15:17:17.427  WARN 64359 --- [rics-registry-0] c.w.s.c.m.WavefrontSdkMetricsRegistry    : Unable to send internal SDK metric

java.io.IOException: attempt to send using closed sender
	at com.wavefront.sdk.common.clients.WavefrontClient.sendMetric(WavefrontClient.java:323) ~[wavefront-sdk-java-2.6.2.jar:na]
	at com.wavefront.sdk.common.metrics.WavefrontSdkMetricsRegistry.run(WavefrontSdkMetricsRegistry.java:163) ~[wavefront-sdk-java-2.6.2.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-04-09 15:17:17.427  WARN 64359 --- [rics-registry-0] c.w.s.c.m.WavefrontSdkMetricsRegistry    : Unable to send internal SDK metric

java.io.IOException: attempt to send using closed sender
	at com.wavefront.sdk.common.clients.WavefrontClient.sendMetric(WavefrontClient.java:323) ~[wavefront-sdk-java-2.6.2.jar:na]
	at com.wavefront.sdk.common.metrics.WavefrontSdkMetricsRegistry.run(WavefrontSdkMetricsRegistry.java:163) ~[wavefront-sdk-java-2.6.2.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
```

The exact same app with this extra configuration line will not emit those  warnings:

```
wavefront.metrics.extract-jvm-metrics=false
```

[Spring Boot devtools](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools) is a development feature that allows you to reduce the feedback loop by restarting a running process, taking into account any code change you've made in the IDE.

When the `ApplicationContext` is closed, any bean that is `Closeable` or has a `close` method will be disposed accordingly. It looks like that something `WavefrontJvmReporter` initiates is not disposed properly and continues to operate a sender that has been closed.

Here is a reproducer: https://github.com/snicoll-scratches/test-wavefront-devtools

* Open the project and run the app from an IDE.
* Change some code, for instance, change the string in `HomeController`. 
* Build the project (compile). This will restart the app automatically
* After a little while the warnings show up.

**Comment by snicoll** [comment]
@oppegard is there anything I can do to help moving this forward?

**Comment by hanwavefront** [comment]
@snicoll This is addressed in the latest version of the Wavefront reporter via https://github.com/wavefrontHQ/wavefront-internal-reporter-java/commit/671da7cb4c53921adbf35567cba79dbfd9ae7c59, so opening a PR to upgrade to the latest SDK version.

**Comment by snicoll** [comment]
Thanks. This issue is now superseded by https://github.com/wavefrontHQ/wavefront-internal-reporter-java/pull/61
