### ISSUE TITLE
Continually face metric point tag value cannot be blank.

### ISSUE THREAD

**Issue by doddatpivotal** [wavefrontHQ/wavefront-spring-boot#26]
I continually see this error in my logs.  Is there some error checking that could be added.

```
java.lang.IllegalArgumentException: metric point tag value cannot be blank for tag key: uri (http.server.requests.max source=todos-api-855459587c-cs4xs exception=[None] method │
│ =[POST] application=[John's Todos Application] service=[todos-api] uri=[] outcome=[SUCCESS] status=[201])                                                                       │
│     at com.wavefront.sdk.common.Utils.metricToLineData(Utils.java:96)                                                                                                           │
│     at io.micrometer.wavefront.WavefrontMeterRegistry.addMetric(WavefrontMeterRegistry.java:367)                                                                                │
│     at io.micrometer.wavefront.WavefrontMeterRegistry.writeTimer(WavefrontMeterRegistry.java:311)                                                                               │
│     at io.micrometer.core.instrument.Meter.match(Meter.java:111)                                                                                                                │
│     at io.micrometer.wavefront.WavefrontMeterRegistry.lambda$publish$0(WavefrontMeterRegistry.java:197)                                                                         │
│     at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)                                                                                                │
│     at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)                                                                                           │
│     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)                                                                                                    │
│     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)                                                                                             │
│     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)                                                                                            │
│     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)                                                                                      │
│     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)                                                                                                    │
│     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)                                                                                                   │
│     at io.micrometer.wavefront.WavefrontMeterRegistry.publish(WavefrontMeterRegistry.java:207)                                                                                  │
│     at io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:48)                                                                            │
│     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                                                  │
│     at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)                                                                                                         │
│     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)                                                    │
│     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)                                                           │
│     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                          │
│     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                          │
│     at java.lang.Thread.run(Thread.java:748)
```

**Comment by snicoll** [comment]
> Is there some error checking that could be added.

Before we decided to do that, we should understand a bit more what's going on with your setup. Is there a way for me to  reproduce this?

**Comment by doddatpivotal** [comment]
This issue is no longer happening after I made many other required changes.  We can close the issue.

**Comment by snicoll** [comment]
Thanks for the feedback. I am still interested to understand how you managed to get this exception as there might still be a bug in Micrometer or in Spring Boot.  If you have a sample, feel free to share it.
